version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "deps"

  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "frontend"
    groups:
      frontend-development-dependencies:
        dependency-type: "development"
        patterns:
          - "*"
    commit-message:
      prefix: "deps"

  - package-ecosystem: "cargo"
    directory: "/src-tauri"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "rust"
    commit-message:
      prefix: "deps"
